package gaia.fabric;

import gaia.GrimoireOfGaia;
import gaia.client.model.AntSalvagerModel;
import gaia.client.model.AntWorkerModel;
import gaia.client.model.AnubisModel;
import gaia.client.model.ArachneModel;
import gaia.client.model.BansheeModel;
import gaia.client.model.BeeModel;
import gaia.client.model.BehenderModel;
import gaia.client.model.BoneKnightModel;
import gaia.client.model.CecaeliaModel;
import gaia.client.model.CentaurModel;
import gaia.client.model.CobbleGolemModel;
import gaia.client.model.CobblestoneGolemModel;
import gaia.client.model.CreepModel;
import gaia.client.model.CreeperGirlModel;
import gaia.client.model.CyclopsModel;
import gaia.client.model.DeathwordModel;
import gaia.client.model.DryadModel;
import gaia.client.model.DullahanModel;
import gaia.client.model.DwarfModel;
import gaia.client.model.EnderDragonGirlModel;
import gaia.client.model.EnderEyeModel;
import gaia.client.model.EnderGirlModel;
import gaia.client.model.FleshLichModel;
import gaia.client.model.GelatinousSlimeModel;
import gaia.client.model.GoblinModel;
import gaia.client.model.GraveMiteModel;
import gaia.client.model.GryphonModel;
import gaia.client.model.GryphonRenderer;
import gaia.client.model.HarpyModel;
import gaia.client.model.HunterModel;
import gaia.client.model.KoboldModel;
import gaia.client.model.MandragoraModel;
import gaia.client.model.MatangoModel;
import gaia.client.model.MermaidModel;
import gaia.client.model.MimicModel;
import gaia.client.model.MinotaurModel;
import gaia.client.model.MinotaurusModel;
import gaia.client.model.MummyModel;
import gaia.client.model.NagaModel;
import gaia.client.model.NineTailsModel;
import gaia.client.model.OniModel;
import gaia.client.model.OrcModel;
import gaia.client.model.SatyressModel;
import gaia.client.model.ShamanModel;
import gaia.client.model.SharkoModel;
import gaia.client.model.SharkoRenderer;
import gaia.client.model.SirenModel;
import gaia.client.model.SlimeGirlModel;
import gaia.client.model.SludgeGirlModel;
import gaia.client.model.SphinxModel;
import gaia.client.model.SporelingModel;
import gaia.client.model.SprigganModel;
import gaia.client.model.SuccubusModel;
import gaia.client.model.ToadModel;
import gaia.client.model.TraderModel;
import gaia.client.model.ValkyrieModel;
import gaia.client.model.WerecatModel;
import gaia.client.model.WitchModel;
import gaia.client.model.WitherCowModel;
import gaia.client.model.WizardHarpyModel;
import gaia.client.model.YukiOnnaModel;
import gaia.client.model.prop.AntHillModel;
import gaia.client.model.prop.ChestModel;
import gaia.client.model.prop.CyanFlowerModel;
import gaia.client.renderer.AntSalvagerRenderer;
import gaia.client.renderer.AntWorkerRenderer;
import gaia.client.renderer.AnubisRenderer;
import gaia.client.renderer.ArachneRenderer;
import gaia.client.renderer.BansheeRenderer;
import gaia.client.renderer.BeeRenderer;
import gaia.client.renderer.BehenderRenderer;
import gaia.client.renderer.BoneKnightRenderer;
import gaia.client.renderer.CecaeliaRenderer;
import gaia.client.renderer.CentaurRenderer;
import gaia.client.renderer.CobbleGolemRenderer;
import gaia.client.renderer.CobblestoneGolemRenderer;
import gaia.client.renderer.CreepRenderer;
import gaia.client.renderer.CreeperGirlRenderer;
import gaia.client.renderer.CyclopsRenderer;
import gaia.client.renderer.DeathwordRenderer;
import gaia.client.renderer.DryadRenderer;
import gaia.client.renderer.DullahanRenderer;
import gaia.client.renderer.DwarfRenderer;
import gaia.client.renderer.EnderDragonGirlRenderer;
import gaia.client.renderer.EnderEyeRenderer;
import gaia.client.renderer.EnderGirlRenderer;
import gaia.client.renderer.FleshLichRenderer;
import gaia.client.renderer.GaiaHorseRenderer;
import gaia.client.renderer.GelatinousSlimeRenderer;
import gaia.client.renderer.GoblinFeralRenderer;
import gaia.client.renderer.GoblinRenderer;
import gaia.client.renderer.GraveMiteRenderer;
import gaia.client.renderer.HarpyRenderer;
import gaia.client.renderer.HunterRenderer;
import gaia.client.renderer.KoboldRenderer;
import gaia.client.renderer.MandragoraRenderer;
import gaia.client.renderer.MatangoRenderer;
import gaia.client.renderer.MermaidRenderer;
import gaia.client.renderer.MimicRenderer;
import gaia.client.renderer.MinotaurRenderer;
import gaia.client.renderer.MinotaurusRenderer;
import gaia.client.renderer.MummyRenderer;
import gaia.client.renderer.NagaRenderer;
import gaia.client.renderer.NineTailsRenderer;
import gaia.client.renderer.OniRenderer;
import gaia.client.renderer.OrcRenderer;
import gaia.client.renderer.SatyressRenderer;
import gaia.client.renderer.ShamanRenderer;
import gaia.client.renderer.SirenRenderer;
import gaia.client.renderer.SlimeGirlRenderer;
import gaia.client.renderer.SludgeGirlRenderer;
import gaia.client.renderer.SphinxRenderer;
import gaia.client.renderer.SporelingRenderer;
import gaia.client.renderer.SprigganRenderer;
import gaia.client.renderer.SuccubusRenderer;
import gaia.client.renderer.ToadRenderer;
import gaia.client.renderer.TraderRenderer;
import gaia.client.renderer.ValkyrieRenderer;
import gaia.client.renderer.WerecatRenderer;
import gaia.client.renderer.WitchRenderer;
import gaia.client.renderer.WizardHarpyRenderer;
import gaia.client.renderer.YukiOnnaRenderer;
import gaia.client.renderer.layer.WitherCowRenderer;
import gaia.client.renderer.prop.AntHillRenderer;
import gaia.client.renderer.prop.ChestRenderer;
import gaia.client.renderer.prop.CyanFlowerRenderer;
import gaia.registry.GaiaRegistry;
import net.minecraft.client.model.HorseModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.renderer.entity.ThrownItemRenderer;
import net.minecraft.client.renderer.item.ItemProperties;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry;
import net.fabricmc.fabric.api.client.rendering.v1.EntityModelLayerRegistry;
import static gaia.client.ClientHandler.*;

public final class FabricClient {
    private FabricClient() {}

    public static void register() {
        BlockRenderLayerMap.INSTANCE.putBlock(GaiaRegistry.BUST_GORGON.get(), net.minecraft.client.renderer.net.minecraft.client.renderer.RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(GaiaRegistry.BUST_SPHINX.get(), RenderType.cutout());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.BUST_VALKYRIE.get(), RenderType.cutout());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.BUST_VAMPIRE.get(), RenderType.cutout());

        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.DOLL_CREEPER_GIRL.get(), RenderType.cutout());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.DOLL_ENDER_GIRL.get(), RenderType.cutout());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.DOLL_SLIME_GIRL.get(), net.minecraft.client.renderer.net.minecraft.client.renderer.RenderType.translucent());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.DOLL_MAID.get(), RenderType.cutout());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.DOLL_DULLAHAN.get(), RenderType.cutout());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.DOLL_MERMAID.get(), RenderType.cutout());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.DOLL_NINE_TAILS.get(), RenderType.cutout());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.DOLL_DRYAD.get(), RenderType.cutout());

        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.DECO_GARDEN_GNOME.get(), RenderType.cutout());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.DECO_MANDRAGORA_POT.get(), RenderType.cutout());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.BUST_MINOTAUR.get(), RenderType.cutout());
        ItemBlockRenderTypes.setRenderLayer(GaiaRegistry.DECO_NEST_HARPY.get(), RenderType.cutout());

        {
            ItemProperties.register(GaiaRegistry.STONE_SHIELD.get(), ResourceLocation.parse("blocking"), (stack, level, livingEntity, i) ->
                    livingEntity != null && livingEntity.isUsingItem() && livingEntity.getUseItem() == stack ? 1.0F : 0.0F);
            ItemProperties.register(GaiaRegistry.IRON_SHIELD.get(), ResourceLocation.parse("blocking"), (stack, level, livingEntity, i) ->
                    livingEntity != null && livingEntity.isUsingItem() && livingEntity.getUseItem() == stack ? 1.0F : 0.0F);
            ItemProperties.register(GaiaRegistry.GOLD_SHIELD.get(), ResourceLocation.parse("blocking"), (stack, level, livingEntity, i) ->
                    livingEntity != null && livingEntity.isUsingItem() && livingEntity.getUseItem() == stack ? 1.0F : 0.0F);
            ItemProperties.register(GaiaRegistry.BONE_SHIELD.get(), ResourceLocation.parse("blocking"), (stack, level, livingEntity, i) ->
                    livingEntity != null && livingEntity.isUsingItem() && livingEntity.getUseItem() == stack ? 1.0F : 0.0F);
            ItemProperties.register(GaiaRegistry.SEASHELL_HAIRPIN.get(), ResourceLocation.parse("available"), (stack, level, livingEntity, i) ->
                    stack.getDamageValue() == 0 ? 1.0F : 0.0F);
        }
        registerEntityRenders();
        registerLayerDefinitions();
    }

private static void registerEntityRenders() {
        EntityRendererRegistry.register(GaiaRegistry.ANT_HILL.getEntityType(), AntHillRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.ANT_WORKER.getEntityType(), AntWorkerRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.ANT_SALVAGER.getEntityType(), AntSalvagerRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.ANUBIS.getEntityType(), AnubisRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.ARACHNE.getEntityType(), ArachneRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.BANSHEE.getEntityType(), BansheeRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.BEE.getEntityType(), BeeRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.BEHENDER.getEntityType(), BehenderRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.BONE_KNIGHT.getEntityType(), BoneKnightRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.CECAELIA.getEntityType(), CecaeliaRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.CENTAUR.getEntityType(), CentaurRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.CHEST.getEntityType(), ChestRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.COBBLE_GOLEM.getEntityType(), CobbleGolemRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.COBBLESTONE_GOLEM.getEntityType(), CobblestoneGolemRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.CREEP.getEntityType(), CreepRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.CYCLOPS.getEntityType(), CyclopsRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.CYAN_FLOWER.getEntityType(), CyanFlowerRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.DEATHWORD.getEntityType(), DeathwordRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.DRYAD.getEntityType(), DryadRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.DULLAHAN.getEntityType(), DullahanRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.DWARF.getEntityType(), DwarfRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.ENDER_EYE.getEntityType(), EnderEyeRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.ENDER_DRAGON_GIRL.getEntityType(), EnderDragonGirlRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.FLESH_LICH.getEntityType(), FleshLichRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.GELATINOUS_SLIME.getEntityType(), GelatinousSlimeRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.GOBLIN.getEntityType(), GoblinRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.GOBLIN_FERAL.getEntityType(), GoblinFeralRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.GRAVEMITE.getEntityType(), GraveMiteRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.GRYPHON.getEntityType(), GryphonRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.HARPY.getEntityType(), HarpyRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.HUNTER.getEntityType(), HunterRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.KOBOLD.getEntityType(), KoboldRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.MANDRAGORA.getEntityType(), MandragoraRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.MATANGO.getEntityType(), MatangoRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.MERMAID.getEntityType(), MermaidRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.MINOTAUR.getEntityType(), MinotaurRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.MINOTAURUS.getEntityType(), MinotaurusRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.MIMIC.getEntityType(), MimicRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.MUMMY.getEntityType(), MummyRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.NAGA.getEntityType(), NagaRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.NINE_TAILS.getEntityType(), NineTailsRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.ONI.getEntityType(), OniRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.ORC.getEntityType(), OrcRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.SATYRESS.getEntityType(), SatyressRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.SHAMAN.getEntityType(), ShamanRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.SHARKO.getEntityType(), SharkoRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.SIREN.getEntityType(), SirenRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.SLUDGE_GIRL.getEntityType(), SludgeGirlRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.SPHINX.getEntityType(), SphinxRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.SPORELING.getEntityType(), SporelingRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.SPRIGGAN.getEntityType(), SprigganRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.SUCCUBUS.getEntityType(), SuccubusRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.TOAD.getEntityType(), ToadRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.VALKYRIE.getEntityType(), ValkyrieRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.WERECAT.getEntityType(), WerecatRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.WITCH.getEntityType(), WitchRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.WITHER_COW.getEntityType(), WitherCowRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.WIZARD_HARPY.getEntityType(), WizardHarpyRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.YUKI_ONNA.getEntityType(), YukiOnnaRenderer::new);

        EntityRendererRegistry.register(GaiaRegistry.TRADER.getEntityType(), TraderRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.CREEPER_GIRL.getEntityType(), CreeperGirlRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.ENDER_GIRL.getEntityType(), EnderGirlRenderer::new);
//        EntityRendererRegistry.register(GaiaRegistry.HOLSTAURUS.getEntityType(), HolstaurusRenderer::new);
        EntityRendererRegistry.register(GaiaRegistry.SLIME_GIRL.getEntityType(), SlimeGirlRenderer::new);
//        EntityRendererRegistry.register(GaiaRegistry.WERESHEEP.getEntityType(), WeresheepRenderer::new);

        EntityRendererRegistry.register(GaiaRegistry.HORSE.getEntityType(), GaiaHorseRenderer::new);

        EntityRendererRegistry.register(GaiaRegistry.SMALL_FIREBALL.get(), (context) -> new ThrownItemRenderer<>(context, 0.75F, true));
        EntityRendererRegistry.register(GaiaRegistry.MAGIC.get(), (context) -> new ThrownItemRenderer<>(context, 0.75F, true));
        EntityRendererRegistry.register(GaiaRegistry.RANDOM_MAGIC.get(), (context) -> new ThrownItemRenderer<>(context, 0.75F, true));
        EntityRendererRegistry.register(GaiaRegistry.WEB.get(), (context) -> new ThrownItemRenderer<>(context, 0.75F, true));
        EntityRendererRegistry.register(GaiaRegistry.BOMB.get(), (context) -> new ThrownItemRenderer<>(context, 0.75F, true));
        EntityRendererRegistry.register(GaiaRegistry.POISON.get(), (context) -> new ThrownItemRenderer<>(context, 0.75F, true));
        EntityRendererRegistry.register(GaiaRegistry.BUBBLE.get(), (context) -> new ThrownItemRenderer<>(context, 0.75F, true));
    }

private static void registerLayerDefinitions() {
        EntityModelLayerRegistry.registerModelLayer(ANT_HILL, AntHillModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(ANT_WORKER, AntWorkerModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(ANT_SALVAGER, AntSalvagerModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(ANUBIS, AnubisModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(ARACHNE, ArachneModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(BANSHEE, BansheeModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(BEE, BeeModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(BEHENDER, BehenderModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(BONE_KNIGHT, BoneKnightModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(CECAELIA, CecaeliaModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(CENTAUR, CentaurModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(CHEST, ChestModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(COBBLE_GOLEM, CobbleGolemModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(COBBLESTONE_GOLEM, CobblestoneGolemModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(CREEP, () -> CreepModel.createBodyLayer(CubeDeformation.NONE));
        EntityModelLayerRegistry.registerModelLayer(CREEP_ARMOR, () -> CreepModel.createBodyLayer(new CubeDeformation(2.0F)));
        EntityModelLayerRegistry.registerModelLayer(CYCLOPS, CyclopsModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(CYAN_FLOWER, CyanFlowerModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(DEATHWORD, DeathwordModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(DRYAD, DryadModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(DULLAHAN, DullahanModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(DWARF, DwarfModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(ENDER_EYE, EnderEyeModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(ENDER_DRAGON_GIRL, EnderDragonGirlModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(FLESH_LICH, FleshLichModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(GELATINOUS_SLIME, GelatinousSlimeModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(GOBLIN, GoblinModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(GOBLIN_FERAL, GoblinModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(GRAVEMITE, GraveMiteModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(GRYPHON, GryphonModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(HARPY, HarpyModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(HUNTER, HunterModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(KOBOLD, KoboldModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(MANDRAGORA, MandragoraModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(MATANGO, MatangoModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(MERMAID, MermaidModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(MINOTAUR, MinotaurModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(MINOTAURUS, MinotaurusModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(MIMIC, MimicModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(MUMMY, MummyModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(NAGA, NagaModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(NINE_TAILS, NineTailsModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(ONI, OniModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(ORC, OrcModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(SATYRESS, SatyressModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(SHAMAN, ShamanModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(SHARKO, SharkoModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(SIREN, SirenModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(SLUDGE_GIRL, SludgeGirlModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(SPHINX, SphinxModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(SPORELING, SporelingModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(SPRIGGAN, SprigganModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(SUCCUBUS, SuccubusModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(TOAD, ToadModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(VALKYRIE, ValkyrieModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(WERECAT, WerecatModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(WITCH, WitchModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(WITHER_COW, WitherCowModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(WIZARD_HARPY, WizardHarpyModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(YUKI_ONNA, YukiOnnaModel::createBodyLayer);

        EntityModelLayerRegistry.registerModelLayer(TRADER, TraderModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(CREEPER_GIRL, CreeperGirlModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(ENDER_GIRL, EnderGirlModel::createBodyLayer);
//        EntityModelLayerRegistry.registerModelLayer(HOLSTAURUS, HolstaurusModel::createBodyLayer);
        EntityModelLayerRegistry.registerModelLayer(SLIME_GIRL, SlimeGirlModel::createBodyLayer);
//        EntityModelLayerRegistry.registerModelLayer(WERESHEEP, WeresheepModel::createBodyLayer);

        EntityModelLayerRegistry.registerModelLayer(HORSE, () -> LayerDefinition.create(HorseModel.createBodyMesh(CubeDeformation.NONE), 64, 64));
    }
}
