package gaia.fabric;

import gaia.registry.GaiaRegistry;
import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.MobCategory;

import java.util.function.Predicate;

public final class FabricBiomeSpawns {
    private FabricBiomeSpawns() {}

    private static Predicate<BiomeSelectionContext> tag(String id) {
        return BiomeSelectors.tag(TagKey.create(Registries.BIOME, ResourceLocation.parse(id)));
    }

    public static void register() {
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_sandy")).and(tag("minecraft:is_badlands").negate()), MobCategory.MONSTER, GaiaRegistry.ANT_HILL.getEntityType(), 20, 1, 1);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_sandy")).and(tag("minecraft:is_badlands").negate()), MobCategory.MONSTER, GaiaRegistry.ANT_SALVAGER.getEntityType(), 20, 2, 5);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_sandy")).and(tag("minecraft:is_badlands").negate()), MobCategory.MONSTER, GaiaRegistry.ANUBIS.getEntityType(), 20, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_sandy")).and(tag("minecraft:is_badlands").negate()), MobCategory.MONSTER, GaiaRegistry.MUMMY.getEntityType(), 100, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_sandy")).and(tag("minecraft:is_badlands").negate()), MobCategory.MONSTER, GaiaRegistry.SPHINX.getEntityType(), 10, 1, 1);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:has_structure/ancient_city").negate()).and(tag("c:is_mushroom").negate()).and(tag("c:no_default_monsters").negate()), MobCategory.MONSTER, GaiaRegistry.ARACHNE.getEntityType(), 80, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:has_structure/ancient_city").negate()).and(tag("c:is_mushroom").negate()).and(tag("c:no_default_monsters").negate()), MobCategory.MONSTER, GaiaRegistry.BONE_KNIGHT.getEntityType(), 40, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:has_structure/ancient_city").negate()).and(tag("c:is_mushroom").negate()).and(tag("c:no_default_monsters").negate()), MobCategory.MONSTER, GaiaRegistry.CREEP.getEntityType(), 80, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:has_structure/ancient_city").negate()).and(tag("c:is_mushroom").negate()).and(tag("c:no_default_monsters").negate()), MobCategory.MONSTER, GaiaRegistry.DEATHWORD.getEntityType(), 40, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:has_structure/ancient_city").negate()).and(tag("c:is_mushroom").negate()).and(tag("c:no_default_monsters").negate()), MobCategory.MONSTER, GaiaRegistry.ENDER_EYE.getEntityType(), 40, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:has_structure/ancient_city").negate()).and(tag("c:is_mushroom").negate()).and(tag("c:no_default_monsters").negate()), MobCategory.MONSTER, GaiaRegistry.FLESH_LICH.getEntityType(), 40, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:has_structure/ancient_city").negate()).and(tag("c:is_mushroom").negate()).and(tag("c:no_default_monsters").negate()), MobCategory.MONSTER, GaiaRegistry.MIMIC.getEntityType(), 40, 1, 1);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_plateau")).and(tag("c:is_cold").negate()).and(tag("c:is_hot").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.BANSHEE.getEntityType(), 40, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_mountain")).and(tag("c:is_hot").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.BANSHEE.getEntityType(), 40, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_plateau")).and(tag("c:is_cold").negate()).and(tag("c:is_hot").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.DULLAHAN.getEntityType(), 100, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_mountain")).and(tag("c:is_hot").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.DULLAHAN.getEntityType(), 100, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_plateau")).and(tag("c:is_cold").negate()).and(tag("c:is_hot").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.DWARF.getEntityType(), 30, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_mountain")).and(tag("c:is_hot").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.DWARF.getEntityType(), 30, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_plateau")).and(tag("c:is_cold").negate()).and(tag("c:is_hot").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.GRYPHON.getEntityType(), 80, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_mountain")).and(tag("c:is_hot").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.GRYPHON.getEntityType(), 100, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_plateau")).and(tag("c:is_cold").negate()).and(tag("c:is_hot").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.VALKYRIE.getEntityType(), 10, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_mountain")).and(tag("c:is_hot").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.VALKYRIE.getEntityType(), 10, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_end")).and(tag("c:is_cold_end")).and(tag("c:is_dry/end")), MobCategory.MONSTER, GaiaRegistry.BEHENDER.getEntityType(), 1, 1, 1);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_end")).and(tag("c:is_cold_end")).and(tag("c:is_dry/end")), MobCategory.MONSTER, GaiaRegistry.ENDER_DRAGON_GIRL.getEntityType(), 1, 1, 1);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_beach")), MobCategory.MONSTER, GaiaRegistry.CECAELIA.getEntityType(), 80, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_aquatic")), MobCategory.MONSTER, GaiaRegistry.CECAELIA.getEntityType(), 80, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_beach")), MobCategory.MONSTER, GaiaRegistry.MERMAID.getEntityType(), 40, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_aquatic")), MobCategory.MONSTER, GaiaRegistry.MERMAID.getEntityType(), 40, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_beach")), MobCategory.MONSTER, GaiaRegistry.SHARKO.getEntityType(), 40, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_aquatic")), MobCategory.MONSTER, GaiaRegistry.SHARKO.getEntityType(), 40, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_swamp")), MobCategory.MONSTER, GaiaRegistry.GELATINOUS_SLIME.getEntityType(), 80, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_swamp")), MobCategory.MONSTER, GaiaRegistry.NAGA.getEntityType(), 30, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_swamp")), MobCategory.MONSTER, GaiaRegistry.SIREN.getEntityType(), 60, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_swamp")), MobCategory.MONSTER, GaiaRegistry.SLUDGE_GIRL.getEntityType(), 100, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_jungle")), MobCategory.MONSTER, GaiaRegistry.COBBLE_GOLEM.getEntityType(), 60, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_jungle")), MobCategory.MONSTER, GaiaRegistry.COBBLESTONE_GOLEM.getEntityType(), 60, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_jungle")), MobCategory.MONSTER, GaiaRegistry.HUNTER.getEntityType(), 60, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_jungle")), MobCategory.MONSTER, GaiaRegistry.SHAMAN.getEntityType(), 60, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_spooky")), MobCategory.MONSTER, GaiaRegistry.MATANGO.getEntityType(), 60, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_spooky")), MobCategory.MONSTER, GaiaRegistry.TOAD.getEntityType(), 80, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_spooky")), MobCategory.MONSTER, GaiaRegistry.WITCH.getEntityType(), 60, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_spooky")), MobCategory.MONSTER, GaiaRegistry.WIZARD_HARPY.getEntityType(), 60, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_plains")).and(tag("minecraft:is_savanna").negate()), MobCategory.MONSTER, GaiaRegistry.CENTAUR.getEntityType(), 20, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_badlands")), MobCategory.MONSTER, GaiaRegistry.CENTAUR.getEntityType(), 20, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_plains")).and(tag("minecraft:is_savanna").negate()), MobCategory.MONSTER, GaiaRegistry.SATYRESS.getEntityType(), 20, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_badlands")), MobCategory.MONSTER, GaiaRegistry.SATYRESS.getEntityType(), 20, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_plains")).and(tag("minecraft:is_savanna").negate()), MobCategory.MONSTER, GaiaRegistry.HARPY.getEntityType(), 100, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_badlands")), MobCategory.MONSTER, GaiaRegistry.HARPY.getEntityType(), 100, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_spooky")), MobCategory.MONSTER, GaiaRegistry.HARPY.getEntityType(), 100, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_plains")).and(tag("minecraft:is_savanna").negate()), MobCategory.MONSTER, GaiaRegistry.MINOTAUR.getEntityType(), 10, 1, 1);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_badlands")), MobCategory.MONSTER, GaiaRegistry.MINOTAUR.getEntityType(), 10, 1, 1);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_spooky")), MobCategory.MONSTER, GaiaRegistry.MINOTAUR.getEntityType(), 10, 1, 1);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_plains")).and(tag("minecraft:is_savanna").negate()), MobCategory.MONSTER, GaiaRegistry.MINOTAURUS.getEntityType(), 80, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_badlands")), MobCategory.MONSTER, GaiaRegistry.MINOTAURUS.getEntityType(), 80, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_spooky")), MobCategory.MONSTER, GaiaRegistry.MINOTAURUS.getEntityType(), 80, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_savanna")), MobCategory.MONSTER, GaiaRegistry.GOBLIN.getEntityType(), 30, 2, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_savanna")), MobCategory.MONSTER, GaiaRegistry.ORC.getEntityType(), 80, 2, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_nether")), MobCategory.MONSTER, GaiaRegistry.SUCCUBUS.getEntityType(), 16, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_nether")), MobCategory.MONSTER, GaiaRegistry.WITHER_COW.getEntityType(), 12, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_coniferous_tree")).and(tag("c:is_snowy").negate()), MobCategory.MONSTER, GaiaRegistry.CYCLOPS.getEntityType(), 40, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_coniferous_tree")).and(tag("c:is_snowy").negate()), MobCategory.MONSTER, GaiaRegistry.NINE_TAILS.getEntityType(), 40, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_coniferous_tree")).and(tag("c:is_snowy").negate()), MobCategory.MONSTER, GaiaRegistry.ONI.getEntityType(), 80, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_coniferous_tree")).and(tag("c:is_snowy").negate()), MobCategory.MONSTER, GaiaRegistry.YUKI_ONNA.getEntityType(), 60, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_coniferous_tree")).and(tag("c:is_snowy").negate()), MobCategory.MONSTER, GaiaRegistry.CYAN_FLOWER.getEntityType(), 60, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_coniferous_tree").negate()).and(tag("c:is_cold/overworld").negate()).and(tag("c:is_hot/overworld").negate()).and(tag("c:is_sparse_vegetation").negate()).and(tag("c:is_spooky").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.BEE.getEntityType(), 80, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_coniferous_tree").negate()).and(tag("c:is_cold/overworld").negate()).and(tag("c:is_hot/overworld").negate()).and(tag("c:is_sparse_vegetation").negate()).and(tag("c:is_spooky").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.DRYAD.getEntityType(), 60, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_coniferous_tree").negate()).and(tag("c:is_cold/overworld").negate()).and(tag("c:is_hot/overworld").negate()).and(tag("c:is_sparse_vegetation").negate()).and(tag("c:is_spooky").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.CYAN_FLOWER.getEntityType(), 60, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_coniferous_tree").negate()).and(tag("c:is_cold/overworld").negate()).and(tag("c:is_hot/overworld").negate()).and(tag("c:is_sparse_vegetation").negate()).and(tag("c:is_spooky").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.SPRIGGAN.getEntityType(), 40, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_coniferous_tree").negate()).and(tag("c:is_cold/overworld").negate()).and(tag("c:is_hot/overworld").negate()).and(tag("c:is_sparse_vegetation").negate()).and(tag("c:is_spooky").negate()).and(tag("c:is_dense_vegetation").negate()), MobCategory.MONSTER, GaiaRegistry.WERECAT.getEntityType(), 80, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_dense_vegetation")).and(tag("c:is_rare")).and(tag("c:is_coniferous_tree").negate()).and(tag("c:is_cold").negate()).and(tag("c:is_hot").negate()).and(tag("c:is_sparse_vegetation").negate()).and(tag("c:is_spooky").negate()), MobCategory.MONSTER, GaiaRegistry.BEE.getEntityType(), 80, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_dense_vegetation")).and(tag("c:is_rare")).and(tag("c:is_coniferous_tree").negate()).and(tag("c:is_cold").negate()).and(tag("c:is_hot").negate()).and(tag("c:is_sparse_vegetation").negate()).and(tag("c:is_spooky").negate()), MobCategory.MONSTER, GaiaRegistry.CYAN_FLOWER.getEntityType(), 60, 1, 2);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_dense_vegetation")).and(tag("c:is_rare")).and(tag("c:is_coniferous_tree").negate()).and(tag("c:is_cold").negate()).and(tag("c:is_hot").negate()).and(tag("c:is_sparse_vegetation").negate()).and(tag("c:is_spooky").negate()), MobCategory.MONSTER, GaiaRegistry.DRYAD.getEntityType(), 60, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_dense_vegetation")).and(tag("c:is_rare")).and(tag("c:is_coniferous_tree").negate()).and(tag("c:is_cold").negate()).and(tag("c:is_hot").negate()).and(tag("c:is_sparse_vegetation").negate()).and(tag("c:is_spooky").negate()), MobCategory.MONSTER, GaiaRegistry.SPRIGGAN.getEntityType(), 40, 2, 4);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("minecraft:is_forest")).and(tag("c:is_dense_vegetation")).and(tag("c:is_rare")).and(tag("c:is_coniferous_tree").negate()).and(tag("c:is_cold").negate()).and(tag("c:is_hot").negate()).and(tag("c:is_sparse_vegetation").negate()).and(tag("c:is_spooky").negate()), MobCategory.MONSTER, GaiaRegistry.WERECAT.getEntityType(), 80, 4, 6);
        BiomeModifications.addSpawn(BiomeSelectors.all().and(tag("minecraft:is_overworld")).and(tag("c:is_snowy")).and(tag("minecraft:is_ocean").negate()).and(tag("minecraft:is_river").negate()).and(tag("minecraft:is_beach").negate()).and(tag("minecraft:is_forest").negate()), MobCategory.MONSTER, GaiaRegistry.KOBOLD.getEntityType(), 60, 4, 6);
    }
}
