package gaia.fabric;

import gaia.registry.GaiaRegistry;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.world.entity.SpawnPlacements;
import net.minecraft.world.entity.SpawnPlacementTypes;
import net.minecraft.world.level.levelgen.Heightmap;

public final class FabricSpawns {
    private FabricSpawns() {}

    public static void registerAttributesAndSpawns() {
        FabricDefaultAttributeRegistry.register(GaiaRegistry.ANT_HILL.getEntityType(), AntHill.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.ANT_WORKER.getEntityType(), AntWorker.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.ANT_SALVAGER.getEntityType(), AntSalvager.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.ANUBIS.getEntityType(), Anubis.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.ARACHNE.getEntityType(), Arachne.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.BANSHEE.getEntityType(), Banshee.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.BEE.getEntityType(), Bee.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.BEHENDER.getEntityType(), Behender.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.BONE_KNIGHT.getEntityType(), BoneKnight.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.CENTAUR.getEntityType(), Centaur.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.CHEST.getEntityType(), Chest.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.COBBLE_GOLEM.getEntityType(), CobbleGolem.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.COBBLESTONE_GOLEM.getEntityType(), CobblestoneGolem.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.CREEP.getEntityType(), Creep.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.CYCLOPS.getEntityType(), Cyclops.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.CYAN_FLOWER.getEntityType(), CyanFlower.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.CECAELIA.getEntityType(), Cecaelia.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.DEATHWORD.getEntityType(), Deathword.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.DRYAD.getEntityType(), Dryad.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.DULLAHAN.getEntityType(), Dullahan.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.DWARF.getEntityType(), Dwarf.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.ENDER_EYE.getEntityType(), EnderEye.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.ENDER_DRAGON_GIRL.getEntityType(), EnderDragonGirl.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.FLESH_LICH.getEntityType(), FleshLich.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.GELATINOUS_SLIME.getEntityType(), GelatinousSlime.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.GOBLIN.getEntityType(), Goblin.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.GOBLIN_FERAL.getEntityType(), GoblinFeral.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.GRAVEMITE.getEntityType(), GraveMite.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.GRYPHON.getEntityType(), Gryphon.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.HARPY.getEntityType(), Harpy.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.HUNTER.getEntityType(), Hunter.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.KOBOLD.getEntityType(), Kobold.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.MANDRAGORA.getEntityType(), Mandragora.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.MATANGO.getEntityType(), Matango.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.MERMAID.getEntityType(), Mermaid.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.MINOTAURUS.getEntityType(), Minotaurus.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.MUMMY.getEntityType(), Mummy.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.MINOTAUR.getEntityType(), Minotaur.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.MIMIC.getEntityType(), Mimic.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.NAGA.getEntityType(), Naga.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.NINE_TAILS.getEntityType(), NineTails.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.ONI.getEntityType(), Oni.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.ORC.getEntityType(), Orc.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.SATYRESS.getEntityType(), Satyress.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.SHAMAN.getEntityType(), Shaman.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.SHARKO.getEntityType(), Sharko.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.SIREN.getEntityType(), Siren.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.SLUDGE_GIRL.getEntityType(), SludgeGirl.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.SPHINX.getEntityType(), Sphinx.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.SPORELING.getEntityType(), Sporeling.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.SPRIGGAN.getEntityType(), Spriggan.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.SUCCUBUS.getEntityType(), Succubus.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.TOAD.getEntityType(), Toad.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.VALKYRIE.getEntityType(), Valkyrie.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.WERECAT.getEntityType(), Werecat.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.WITCH.getEntityType(), Witch.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.WITHER_COW.getEntityType(), WitherCow.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.WIZARD_HARPY.getEntityType(), WizardHarpy.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.YUKI_ONNA.getEntityType(), YukiOnna.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.TRADER.getEntityType(), Trader.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.CREEPER_GIRL.getEntityType(), CreeperGirl.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.ENDER_GIRL.getEntityType(), EnderGirl.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.HOLSTAURUS.getEntityType(), Holstaurus.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.SLIME_GIRL.getEntityType(), SlimeGirl.createAttributes().build());
        FabricDefaultAttributeRegistry.register(GaiaRegistry.WERESHEEP.getEntityType(), Weresheep.createAttributes().build());

        SpawnPlacements.register(GaiaRegistry.ANT_HILL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, AntHill::checkAntHillSpawnRules);
        SpawnPlacements.register(GaiaRegistry.ANT_WORKER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, AntWorker::checkAntWorkerSpawnRules);
        SpawnPlacements.register(GaiaRegistry.ANT_SALVAGER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, AntSalvager::checkAntSalvagerSpawnRules);
        SpawnPlacements.register(GaiaRegistry.ARACHNE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Arachne::checkArachneSpawnRules);
        SpawnPlacements.register(GaiaRegistry.ANUBIS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Anubis::checkAnubisSpawnRules);
        SpawnPlacements.register(GaiaRegistry.BANSHEE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Banshee::checkBansheeSpawnRules);
        SpawnPlacements.register(GaiaRegistry.BEE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Bee::checkBeeSpawnRules);
        SpawnPlacements.register(GaiaRegistry.BEHENDER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Behender::checkBehenderSpawnRules);
        SpawnPlacements.register(GaiaRegistry.BONE_KNIGHT.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, BoneKnight::checkBoneKnightSpawnRules);
        SpawnPlacements.register(GaiaRegistry.CECAELIA.getEntityType(), SpawnPlacementTypes.IN_WATER, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Cecaelia::checkCecaeliaSpawnRules);
        SpawnPlacements.register(GaiaRegistry.CENTAUR.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Centaur::checkCentaurSpawnRules);
        SpawnPlacements.register(GaiaRegistry.CHEST.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Chest::checkChestSpawnRules);
        SpawnPlacements.register(GaiaRegistry.COBBLE_GOLEM.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, CobbleGolem::checkCobbleGolemSpawnRules);
        SpawnPlacements.register(GaiaRegistry.COBBLESTONE_GOLEM.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, CobblestoneGolem::checkCobblestoneGolemSpawnRules);
        SpawnPlacements.register(GaiaRegistry.CREEP.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Creep::checkCreepSpawnRules);
        SpawnPlacements.register(GaiaRegistry.CYCLOPS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Cyclops::checkCyclopsSpawnRules);
        SpawnPlacements.register(GaiaRegistry.CYAN_FLOWER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, CyanFlower::checkCyanFlowerSpawnRules);
        SpawnPlacements.register(GaiaRegistry.DEATHWORD.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Deathword::checkDeathwordSpawnRules);
        SpawnPlacements.register(GaiaRegistry.DRYAD.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Dryad::checkDryadSpawnRules);
        SpawnPlacements.register(GaiaRegistry.DULLAHAN.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Dullahan::checkDullahanSpawnRules);
        SpawnPlacements.register(GaiaRegistry.DWARF.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Dwarf::checkDwarfSpawnRules);
        SpawnPlacements.register(GaiaRegistry.ENDER_EYE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, EnderEye::checkEnderEyeSpawnRules);
        SpawnPlacements.register(GaiaRegistry.ENDER_DRAGON_GIRL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, EnderDragonGirl::checkEnderDragonGirlSpawnRules);
        SpawnPlacements.register(GaiaRegistry.FLESH_LICH.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, FleshLich::checkFleshLichSpawnRules);
        SpawnPlacements.register(GaiaRegistry.GELATINOUS_SLIME.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, GelatinousSlime::checkGelatinousSlimeSpawnRules);
        SpawnPlacements.register(GaiaRegistry.GOBLIN.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Goblin::checkGoblinSpawnRules);
        SpawnPlacements.register(GaiaRegistry.GOBLIN_FERAL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, GoblinFeral::checkGoblinFeralSpawnRules);
        SpawnPlacements.register(GaiaRegistry.GRAVEMITE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, GraveMite::checkMiteSpawnRules);
        SpawnPlacements.register(GaiaRegistry.GRYPHON.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Gryphon::checkGryphonSpawnRules);
        SpawnPlacements.register(GaiaRegistry.HARPY.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Harpy::checkHarpySpawnRules);
        SpawnPlacements.register(GaiaRegistry.HUNTER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Hunter::checkHunterSpawnRules);
        SpawnPlacements.register(GaiaRegistry.KOBOLD.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Kobold::checkKoboldSpawnRules);
        SpawnPlacements.register(GaiaRegistry.MANDRAGORA.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Mandragora::checkMandragoraSpawnRules);
        SpawnPlacements.register(GaiaRegistry.MATANGO.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Matango::checkMatangoSpawnRules);
        SpawnPlacements.register(GaiaRegistry.MERMAID.getEntityType(), SpawnPlacementTypes.IN_WATER, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Mermaid::checkMermaidSpawnRules);
        SpawnPlacements.register(GaiaRegistry.MINOTAUR.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Minotaur::checkMinotaurSpawnRules);
        SpawnPlacements.register(GaiaRegistry.MINOTAURUS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Minotaurus::checkMinotaurusSpawnRules);
        SpawnPlacements.register(GaiaRegistry.MUMMY.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Mummy::checkMummySpawnRules);
        SpawnPlacements.register(GaiaRegistry.MIMIC.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Mimic::checkMimicSpawnRules);
        SpawnPlacements.register(GaiaRegistry.NAGA.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Naga::checkNagaSpawnRules);
        SpawnPlacements.register(GaiaRegistry.NINE_TAILS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, NineTails::checkNineTailsSpawnRules);
        SpawnPlacements.register(GaiaRegistry.ONI.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Oni::checkOniSpawnRules);
        SpawnPlacements.register(GaiaRegistry.ORC.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Orc::checkOrcSpawnRules);
        SpawnPlacements.register(GaiaRegistry.SATYRESS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Satyress::checkSatyressSpawnRules);
        SpawnPlacements.register(GaiaRegistry.SHAMAN.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Shaman::checkShamanSpawnRules);
        SpawnPlacements.register(GaiaRegistry.SHARKO.getEntityType(), SpawnPlacementTypes.IN_WATER, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Sharko::checkSharkoSpawnRules);
        SpawnPlacements.register(GaiaRegistry.SIREN.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Siren::checkSirenSpawnRules);
        SpawnPlacements.register(GaiaRegistry.SLUDGE_GIRL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, SludgeGirl::checkSludgeGirlSpawnRules);
        SpawnPlacements.register(GaiaRegistry.SPHINX.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Sphinx::checkSphinxSpawnRules);
        SpawnPlacements.register(GaiaRegistry.SPORELING.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Sporeling::checkSporelingSpawnRules);
        SpawnPlacements.register(GaiaRegistry.SPRIGGAN.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Spriggan::checkSprigganSpawnRules);
        SpawnPlacements.register(GaiaRegistry.SUCCUBUS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Succubus::checkSuccubusSpawnRules);
        SpawnPlacements.register(GaiaRegistry.TOAD.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Toad::checkToadSpawnRules);
        SpawnPlacements.register(GaiaRegistry.VALKYRIE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Valkyrie::checkValkyrieSpawnRules);
        SpawnPlacements.register(GaiaRegistry.WERECAT.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Werecat::checkWerecatSpawnRules);
        SpawnPlacements.register(GaiaRegistry.WITCH.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Witch::checkWitchSpawnRules);
        SpawnPlacements.register(GaiaRegistry.WITHER_COW.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, WitherCow::checkWitherCowSpawnRules);
        SpawnPlacements.register(GaiaRegistry.WIZARD_HARPY.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, WizardHarpy::checkWizardHarpySpawnRules);
        SpawnPlacements.register(GaiaRegistry.YUKI_ONNA.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, YukiOnna::checkYukiOnnaSpawnRules);
        SpawnPlacements.register(GaiaRegistry.TRADER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Trader::checkMobSpawnRules);
        SpawnPlacements.register(GaiaRegistry.CREEPER_GIRL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, CreeperGirl::checkMobSpawnRules);
        SpawnPlacements.register(GaiaRegistry.ENDER_GIRL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, EnderGirl::checkMobSpawnRules);
        SpawnPlacements.register(GaiaRegistry.HOLSTAURUS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Holstaurus::checkMobSpawnRules);
        SpawnPlacements.register(GaiaRegistry.SLIME_GIRL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, SlimeGirl::checkMobSpawnRules);
        SpawnPlacements.register(GaiaRegistry.WERESHEEP.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Weresheep::checkMobSpawnRules);
        SpawnPlacements.register(GaiaRegistry.HORSE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Animal::checkAnimalSpawnRules);
    }
}
